using Content.Client._RMC14.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Control;

namespace Content.Client._RMC14.Overwatch;

[GenerateTypedNameReferences]
public sealed partial class OverwatchConsoleWindow : RMCPopOutWindow
{
    protected override Control Control => Wrapper;

    public OverwatchConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        UnavailableOverlay.CanKeyboardFocus = true;
        UnavailableOverlay.MouseFilter = MouseFilterMode.Ignore;
    }

    public void SetUnavailable(bool unavailable)
    {
        Wrapper.ModulateSelfOverride = unavailable ? Color.FromHex("#9A9A9A8C") : null;
        UnavailableOverlay.Visible = unavailable;
        UnavailableOverlay.MouseFilter = unavailable ? MouseFilterMode.Stop : MouseFilterMode.Ignore;

        if (unavailable)
            UnavailableOverlay.GrabKeyboardFocus();
        else if (UnavailableOverlay.HasKeyboardFocus())
            UnavailableOverlay.ReleaseKeyboardFocus();
    }
}
